name: Fog18
main: com.minikloon.fog18.Fog18Plugin
version: 1.0

commands:
  gamestate:
    description: Send a game state packet
    usage: /gamestate reason value
  fog:
    description: Send fog packet
    usage: /fog [value]
  deepfog:
    description: Send fog packet with a different 8
    usage: /deepfog [value]
  biome:
    description: Sets the biome around you
    usage: /biome [enum]
  blindness:
    description: Give you blindness
    usage: /blindness [duration]
  nightvision:
    description: Toggles night vision
    aliases:
      - nv
    usage: /nightvision
  nvtick:
    description: Sends night vision for a few ticks
    usage: /nvtick
  env:
    description: Sends you to a world with a particular environment
    usage: /end [environment index]